### ISSUE TITLE
Clarification on Safari's behaviour for fixed position elements

### ISSUE THREAD

**Issue by tpodder** [bokand/bokand.github.io#5]
The page https://theres-waldo.github.io/mozilla-testcases/bug1473699.html was tested in Safari on an iPhone simulator and the behaviour observed was that the fixed position elements were being attached to the visual viewport when we zoom out to the minimum scale. However, the explainer document states that the behaviour of fixed position elements on Safari is such that the fixed position elements are attached to the layout viewport when we zoom out to minimum-scale. Do you know if Safari has perhaps had a recent change in behaviour that hasn't been reflected in the explainer document yet?

**Comment by theres-waldo** [comment]
> It sounds to me (correct me if I'm wrong) like what you're describing is that the fixed boxes are at the correct locations when you're fully zoomed out? And zooming in makes them move offscreen.

Actually, we were trying to reproduce the scenario where in the fully zoomed-out state, the fixed boxes move away from the edge of the screen because they are fixed to the ICB, which is now smaller than the visual viewport. That is, we're trying to reproduce the scenario where the rendering looks like [this](https://camo.githubusercontent.com/f270f57de95fadd542ac7c34cf66a37c95b47434/68747470733a2f2f626f6b616e642e6769746875622e696f2f76696577706f72742f45646765466978656456696577706f72742d322e706e67), with Safari, but we're not able to with the mentioned testcase.

We were wondering if that's because our testcase is failing to exercise the necessary set of conditions, or because Safari has changed their behaviour.

**Comment by theres-waldo** [comment]
(To provide some background: we are trying to figure out how to handle, in Firefox, the case where the ICB is narrower than the visual viewport, and we're trying to understand the behaviour of other browsers. We believe we understand Chrome's model - size the fixed viewport to the minimum scale size, not to the ICB size - but are confused about Safari's model.)

**Comment by bokand** [comment]
Ah, sorry - I misunderstood, that makes sense now.

So IIRC - that situation wasn't actually possible in Safari:

> A consequence of this is that if the user can zoom out to see more than the ICB (Window Phone, but not Safari)

I think Safari should prevent you from zooming out further than the ICB

**Comment by tpodder** [comment]
We tested the behaviour of Safari on an iPhone simulator for [this](https://theres-waldo.github.io/mozilla-testcases/bug1473699.html) test page. On this page, we believe the ICB width is the width at which the text on the page wraps. However, we found it was possible to zoom out beyond this width. It could be possible that the behaviour of Safari has been updated. Could you please clarify this?

**Comment by theres-waldo** [comment]
cc @mstange

As this is ultimately a question about Safari's behaviour, is there a Safari developer we could ask about this?

**Comment by theres-waldo** [comment]
@smfr Perhaps you could route this question about Safari's behaviour to someone who would know the answer?

**Comment by smfr** [comment]
Safari lets you zoom out past ICB size because historically it allowed this, and then sites expected that content outside of the ICB would be visible. I don't think we can change this now.

Furthermore, I think it would be odd if position:fixed things detected from the screen edges when zooming out past ICB size, so when implementing visual viewports that's what I did (there's no spec for this).

**Comment by theres-waldo** [comment]
Thanks! So, just to help me understand the conceptual model here: does Safari attach position:fixed elements to "whichever of the visual viewport or the ICB is larger at the current zoom level"?

**Comment by smfr** [comment]
So logically having a visual viewport larger than the layout viewport doesn't really make sense, but it happens in this zoomed-out case and there's some amount of special-casing in the code for it. But, yes, the "whichever is larger" holds.

**Comment by theres-waldo** [comment]
Ok, thanks, I believe we understand Safari's model now. It seems attractive from a UX point of view; we'll investigate how feasible it is to implement in Firefox.

I'm going to leave this issue open to track updating the explainer document to reflect Safari's current behaviour.

**Comment by theres-waldo** [comment]
It does, thanks!
